version: "3"
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: borders
      MARIADB_USER: borders
      MARIADB_PASSWORD: borders
      MARIADB_DATABASE: borders
    ports:
      - 3306:3306

